package gui;

import controller.FlexController;

import javax.swing.*;
import java.awt.*;

public class MainWindow extends JFrame {
    private JPanel panelMain;
    private JTextField textFieldWorkedHours;
    private JTextField textFieldPlannedHours;
    private JLabel labelHeader;
    private JLabel labelWorkedHours;
    private JLabel labelPlannedHours;
    private JLabel labelBalance;
    private JTextField textFieldBalance;
    private JButton buttonShowTimeLogs;
    private JScrollPane scrollPaneComment;
    private FlexController flexController;


    public MainWindow() {
        $$$setupUI$$$();
        this.flexController = new FlexController(7.5);
        textFieldPlannedHours.setText(String.valueOf(flexController.getDueHours()));
    }

//    public static void main(String[] args) {
//        MainWindow mw = new MainWindow();
//        mw.run(mw);
//
//    }

    private void run(MainWindow mw) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        JFrame frame = new JFrame("FlexTid");
        frame.setContentPane(mw.panelMain);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 3, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.setMinimumSize(new Dimension(600, 450));
        panelMain.setName("FlexTid");
        panelMain.setPreferredSize(new Dimension(600, 450));
        textFieldWorkedHours = new JTextField();
        textFieldWorkedHours.setMaximumSize(new Dimension(78, 24));
        textFieldWorkedHours.setMinimumSize(new Dimension(78, 24));
        textFieldWorkedHours.setPreferredSize(new Dimension(78, 24));
        textFieldWorkedHours.setText("");
        panelMain.add(textFieldWorkedHours, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelHeader = new JLabel();
        Font labelHeaderFont = this.$$$getFont$$$("Calibri", -1, 22, labelHeader.getFont());
        if (labelHeaderFont != null) labelHeader.setFont(labelHeaderFont);
        labelHeader.setText("Registrera tid");
        panelMain.add(labelHeader, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldBalance = new JTextField();
        textFieldBalance.setMinimumSize(new Dimension(78, 24));
        textFieldBalance.setPreferredSize(new Dimension(78, 24));
        panelMain.add(textFieldBalance, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelBalance = new JLabel();
        Font labelBalanceFont = this.$$$getFont$$$("Calibri", -1, 12, labelBalance.getFont());
        if (labelBalanceFont != null) labelBalance.setFont(labelBalanceFont);
        labelBalance.setText("Tidssaldo: ");
        panelMain.add(labelBalance, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonShowTimeLogs = new JButton();
        buttonShowTimeLogs.setMaximumSize(new Dimension(300, 24));
        buttonShowTimeLogs.setMinimumSize(new Dimension(78, 24));
        buttonShowTimeLogs.setPreferredSize(new Dimension(150, 24));
        buttonShowTimeLogs.setText("Visa registreringar");
        panelMain.add(buttonShowTimeLogs, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelPlannedHours = new JLabel();
        Font labelPlannedHoursFont = this.$$$getFont$$$("Calibri", -1, 12, labelPlannedHours.getFont());
        if (labelPlannedHoursFont != null) labelPlannedHours.setFont(labelPlannedHoursFont);
        labelPlannedHours.setText("Planerad arbetstid: ");
        panelMain.add(labelPlannedHours, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 3, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldPlannedHours = new JTextField();
        textFieldPlannedHours.setMinimumSize(new Dimension(78, 24));
        textFieldPlannedHours.setPreferredSize(new Dimension(78, 24));
        panelMain.add(textFieldPlannedHours, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        scrollPaneComment = new JScrollPane();
        panelMain.add(scrollPaneComment, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        labelWorkedHours = new JLabel();
        Font labelWorkedHoursFont = this.$$$getFont$$$("Calibri", -1, 12, labelWorkedHours.getFont());
        if (labelWorkedHoursFont != null) labelWorkedHours.setFont(labelWorkedHoursFont);
        labelWorkedHours.setText("Skriv in din arbetade tid: ");
        panel1.add(labelWorkedHours, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panelMain.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 24), new Dimension(-1, 24), 2, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
